import { Metadata } from "next"
import Link from "next/link"

export const metadata: Metadata = {
  title: 'Next.js + Search Starter',
  description: 'Generated by create next app',
}


export default function SearchLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <div>
    <Link href='/'>
      <p className='bg-gradient-to-r from-blue-500 to-purple-600 
                    hover:from-pink-500 hover:to-orange-500
                    text-white font-bold py-2 px-4 rounded
                    transition-all duration-500 ease-linear 
                    fixed bottom-0 right-0 m-4'
      >
        Go back
      </p>
    </Link>
    {children}

  </div>
}