import { Metadata } from "next"

export const metadata: Metadata = {
  title: 'Next.js + Search Starter',
  description: 'Generated by create next app',
}


export default function SearchLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return <div>{children}</div>
  }